version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: saturday
    time: "21:00"
    timezone: Europe/Amsterdam
  labels:
  - build-infra

