language: php

php:
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"

env:
  - DOKUWIKI=master
  - DOKUWIKI=stable
  - DOKUWIKI=old-stable

before_install:
  - wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh

install:
  - sh travis.sh

script:
  - cd _test && phpunit --stderr --group plugin_socialcards

matrix:
  allow_failures:
    - php: "7.0"
      env: DOKUWIKI=old-stable
