name: 'CI'

on: [ push, pull_request, workflow_dispatch ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.2', '8.5' ]
        dokuwiki-branch: [ 'master', 'stable' ]

    uses: mprins/.github/.github/workflows/test.yml@main
    with:
      php-version: "${{ matrix.php-version }}"
      dokuwiki-branch: "${{ matrix.dokuwiki-branch }}"