name: 'Repository Maintenance'

on:
  schedule:
    - cron: '11 3 * * 6'

jobs:
  lock:
    runs-on: ubuntu-latest
    name: 'Lock stale issues and PRs'
    steps:
      - uses: dessant/lock-threads@v3
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: '90'
          exclude-any-issue-labels: 'upstream, help-wanted'
          pr-inactive-days: '60'
