name: PHP Code Style

on: [pull_request]

jobs:
    phpcs:
        name: PHP CodeSniffer
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '7.4'
                tools: cs2pr, phpcs

            - name: retrieve script
              run: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh

            - name: Install DokuWiki
              env:
                  CI_SERVER: 1
                  DOKUWIKI : master
              run: sh travis.sh

            - name: run PHP codesniffer
              continue-on-error: true
              run: phpcs -v --standard=_test/phpcs_MigrationAdjustments.xml --report-full --report-checkstyle=./phpcs-report.xml lib/plugins/socialcards

            - name: Annotate PR
              run: cs2pr ./phpcs-report.xml
